export const UserActionsTypes = {
  GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FALIURE: 'GET_CURRENT_USER_FALIURE',
};
