export const ADD_CART_ITEMS = ' ADD_CART_ITEMS';
export const REMOVE_CART_ITEMS = ' REMOVE_CART';
export const ADD_SHOPLIST_ITEMS = ' ADD_SHOP_ITEMS';
export const REMOVE_SHOPLIST_ITEMS = ' REMOVE_SHOP_ITEMS';
export const SAVE_FOR_LATER = ' SAVE_FOR_LATER';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const MOVE_TO_CART = ' MOVE_TO_CART';
export const DEL_FROM_SAVELATER = 'DEL_FROM_SAVELATER';
