export const lightTheme = {
  colorBackgroundLight: '#f4f4f4',
  colorBackgroundMedium: '#f4f4f4',
  colorBackgroundDark: '#f4f4f4',
  colorExchangeBackground: 'aliceblue',
  colorBodyBackground: '#e9ebff',
  colorText: '#363636',
  colorTransactionBorder: '#f0e2e7',
  colorCardBorder: '#f4f4f4',
  colorButtonGreen: '#2ecc71',
  colorButtonRed: '#ff3838',
  colorButtonPink: '#ee1a75',
  colorButtonBorder: 'white',
  colorFilterHover: '#bdc3c7',
  colorAuctionBackground: 'rgb(245, 235, 235)',
  colorWhite: 'black',
  colorAuctionInput: '#ccc',
  colorStockLabel: '#464646',
  colorChartBackground: 'white',
  colorChartBorder: 'white',
  colorStockText: '#540075',
  colorNavbarLink: '#041484',
  colorActiveLink: '#e30464',
};
export const darkTheme = {
  colorBackgroundLight: '#27262D',
  colorBackgroundMedium: '#1D1C22',
  colorBackgroundDark: '#0e0e11',
  colorExchangeBackground: 'var(--colorBackgroundMedium)',
  colorBodyBackground: 'var(--colorBackgroundLight)',
  colorText: '#E1E1EC',
  colorTransactionBorder: 'rgb(76, 39, 52)',
  colorCardBorder: 'rgb(51, 55, 57)',
  colorButtonGreen: '#1d8147',
  colorButtonRed: '#9e0000',
  colorButtonPink: '#c70f5f',
  colorButtonBorder: 'var(--colorButtonPink)',
  colorFilterHover: '#3a3f42',
  colorAuctionBackground: '#2e1717',
  colorWhite: '#fff',
  colorAuctionInput: 'white',
  colorStockLabel: 'var(--colorWhite)',
  colorChartBackground: '#241212',
  colorChartBorder: '#34383a',
  colorStockText: '#cf56ff',
  colorNavbarLink: '#7eb2fb',
  colorActiveLink: '#fb2e86',
};
