export const BankActionTypes = {
  SET_CURRENCY_EXCHANGE_RATES: 'SET_CURRENCY_EXCHANGE_RATES',
  SET_BANK_CURRENCIES: 'SET_BANK_CURRENCIES',
  GET_CURRENCY_EXCHANGE_RATES_START: 'GET_CURRENCY_EXCHANGE_RATES_START',
  GET_CURRENCY_EXCHANGE_RATES_SUCCESS: 'GET_CURRENCY_EXCHANGE_RATES_SUCCESS',
  GET_CURRENCY_EXCHANGE_RATES_FALIURE: 'GET_CURRENCY_EXCHANGE_RATES_FALIURE',
};
